### PR TITLE
feat(tokens): generate dark charts tokens file

### LINKED ISSUE #32: Generate dark chart tokens
Dark tokens are now in Figma and need to be exported into their own dark chart .scss file.

### PR DESCRIPTION
**Pull request by srambach**
@lboehling @mcoker Please verify that 1) the tokens that have changed in _tokens-charts.scss look correct and 2) the contents of _tokens-charts-dark.scss look correct and that's the way we want to have the tokens arranged in the files.

Fixes #32

### CODE REVIEW

**Comment by mcoker** [comment]
IMO we can call the chart tokens whatever we want as long as we have vars for all of the style bits that existed before. I'll defer to @lboehling on the naming unless you'd like some specific feedback from me. What's there looks good to me though! 👍👍

**Comment by lboehling** [comment]
Everything in there looks correct to me, too! I tried to keep the variables similarly named to current charts because I wasn't familiar with how victory consumed them. I'm open to adjusting the names if we want them to be more semantic. 

I do not see any of the string variables I entered in Figma, though.
image
image

I wasn't sure if these would export properly from Figma, so maybe that's just a limit to what Figma variables can do?

**Comment by srambach** [comment]
Hmm. @lboehling those variables aren't getting exported to the .json so that's why they aren't in the .scss. I'll put in an issue to find out why.

**Comment by srambach** [comment]
Follow up to get text variables: #34

**Pull request merged**
