### PR TITLE
update build and add custom transforms

### LINKED ISSUE #1: improve design token (JSON) -> SCSS conversion
Leverage style-dictionary's [transformations](https://amzn.github.io/style-dictionary/#/transforms) and [formatting](https://amzn.github.io/style-dictionary/#/formats) to get properly formatted/useful SCSS.

Use the JSON design-tokens (which you can assumer are formatted appropriately to match [W3C Design Token spec](https://design-tokens.github.io/community-group/format/#design-token))

Some known transformations or considerations:
- Delimiters (--)
- preserve (or add) units (usually `px`) on dimensions
- Ensure semantic dimension tokens maintain links to base tokens
- Can we run style dictionary without having to strip out the $ from the json formatted design tokens?

Goal:
- style dictionary is spitting out SCSS which needs no manual updates before being consumed by Core.

### PR DESCRIPTION
**Pull request by kmcfaul**
Closes #1 

Instead of using the basic built in style dictionary build command this expands the build script to include extra logic setting up custom transforms that are applied to the Json tokens. It also adds a custom transform group that all our configs can share.

Also removes some unused configs.

### CODE REVIEW

**Comment by srambach** [comment]
Great! 🎉 Could we look together at the CSS outputs sometime? Maybe these should be checked in to a dist directory?

**Review by srambach — APPROVED** [review]
Looks great!!! 🎉

**Comment by kmcfaul** [comment]
Adding the build directory to the repo to allow easy access to the build SCSS files (not requiring the repo to be cloned/built locally). Future PRs that would effect the SCSS output should be rebuilding and recommitting the updated files automatically but there is the possibility of these files getting out of date, so we can remove this from the repo down the line if it becomes a problem. Also added a readme note.

**Review by srambach — APPROVED** [review]
Thanks for going over it with me! 😎

**Pull request merged**
