### PR TITLE
Add Figma export plugin

### PR DESCRIPTION
**Pull request by mfrances17**
Closes https://github.com/patternfly/design-tokens/issues/2.

This Figma plugin will export the variables out of Figma and separate them into JSON files that can be used by the style dictionary process. It's all written in vanilla JS. My goal for this pass of the plugin was to produce the exact JSON files that we are consuming now, without the manual effort.

See README.md for complete instructions on how to install/use so it can be tested.

**Refactoring/future work**
- In order to satisfy the issue above, this version only handles exporting of variables, it does not handle import. That should probably be tracked/handled in a future issue, if it is needed.
- This version does not export variable descriptions - that should probably be investigated as an additional feature.
- Ideally, the plugin should be refactored as typescript instead of vanilla js, if it is deemed worth the effort.

### CODE REVIEW

**Review by srambach — COMMENTED** [review]
Just a couple of comments/questions:
- Could this be renamed to something more like Export PatternFly Tokens? It's pretty specific to PatternFly.
- Would it be possible to further automate downloading the files? At a minimum, it would be nice to separate the list into files for the base folder and files for the dark folder.

**Comment by mfrances17** [comment]
> * Could this be renamed to something more like Export PatternFly Tokens? It's pretty specific to PatternFly.
Yep, definitely can be renamed to anything we want.

> * Would it be possible to further automate downloading the files? At a minimum, it would be nice to separate the list into files for the base folder and files for the dark folder.
So, the problem here is that I encountered many issues trying to save files to disk using javascript via a browser. The solution I eventually went _would_ actually do it but because the browser needs to prompt the user with the download modal (and I can't get that handle), the code will fail because it outpaces the ability to click/dismiss the dialog. Even with sleeps and promises.

The other possible solution I considered was to import something like the jszip library and create the files and folder structure within a zip and have the user download one zipped file. I personally preferred using the individual links because maybe the user changed just a subset, but that was just my opinion and we can go that route if it's preferred.

**Comment by srambach** [comment]
BTW, your instructions are great! Nice job.

**Comment by nicolethoen** [comment]
+1 instructions are great! it looks like it all worked for me :)

**Review by wise-king-sullyman — APPROVED** [review]
If this is functionality we'll want to maintain long term I'd love to have some tests and I have a few thoughts for how some of the logic can be simplified, but none of that is blocking for me and the functionality seems solid 🔥

**Comment by srambach** [comment]
> > * Could this be renamed to something more like Export PatternFly Tokens? It's pretty specific to PatternFly.
> 
> Yep, definitely can be renamed to anything we want.
Great - so Export PatternFly Tokens?

**Review by srambach — APPROVED** [review]
Thanks @mfrances17 I used the export and it looks good. I will say it is still a bit of manual/mental work to put the files into the right place, so I'd like to make a follow-on to export all at once to a specified place. I think you said this could at least be done by exporting a zip file.

**Pull request merged**
